/*
 * generated by Xtext 2.13.0
 */
package uofa.lbirdsey.castle.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCASLScopeProvider extends DelegatingScopeProvider {
}
