/*
 * generated by Xtext 2.12.0
 */
package uofa.lbirdsey.castle.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCASLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(uofa.lbirdsey.castle.casl.CaslPackage.eINSTANCE);
		return result;
	}
	
}
