/*
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class CASLRuntimeModule extends AbstractCASLRuntimeModule {
}
