/**
 * generated by Xtext 2.13.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Agent Type Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.Agent_Type_Name#getAgent_type_name <em>Agent type name</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getAgent_Type_Name()
 * @model
 * @generated
 */
public interface Agent_Type_Name extends EObject
{
  /**
   * Returns the value of the '<em><b>Agent type name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Agent type name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Agent type name</em>' attribute.
   * @see #setAgent_type_name(String)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getAgent_Type_Name_Agent_type_name()
   * @model
   * @generated
   */
  String getAgent_type_name();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Agent_Type_Name#getAgent_type_name <em>Agent type name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Agent type name</em>' attribute.
   * @see #getAgent_type_name()
   * @generated
   */
  void setAgent_type_name(String value);

} // Agent_Type_Name
