/**
 * generated by Xtext 2.13.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CASL Macro Display</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.CASL_Macro_Display#getRepresentationType <em>Representation Type</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.CASL_Macro_Display#getToProject <em>To Project</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getCASL_Macro_Display()
 * @model
 * @generated
 */
public interface CASL_Macro_Display extends CASL_Macro
{
  /**
   * Returns the value of the '<em><b>Representation Type</b></em>' attribute.
   * The literals are from the enumeration {@link uofa.lbirdsey.castle.casl.LayoutType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Representation Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Representation Type</em>' attribute.
   * @see uofa.lbirdsey.castle.casl.LayoutType
   * @see #setRepresentationType(LayoutType)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getCASL_Macro_Display_RepresentationType()
   * @model
   * @generated
   */
  LayoutType getRepresentationType();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.CASL_Macro_Display#getRepresentationType <em>Representation Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Representation Type</em>' attribute.
   * @see uofa.lbirdsey.castle.casl.LayoutType
   * @see #getRepresentationType()
   * @generated
   */
  void setRepresentationType(LayoutType value);

  /**
   * Returns the value of the '<em><b>To Project</b></em>' containment reference list.
   * The list contents are of type {@link uofa.lbirdsey.castle.casl.Expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To Project</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Project</em>' containment reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getCASL_Macro_Display_ToProject()
   * @model containment="true"
   * @generated
   */
  EList<Expression> getToProject();

} // CASL_Macro_Display
