/**
 * generated by Xtext 2.12.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>CASL Macro Populate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.CASL_Macro_Populate#getInitNum <em>Init Num</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.CASL_Macro_Populate#getEnt <em>Ent</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.CASL_Macro_Populate#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getCASL_Macro_Populate()
 * @model
 * @generated
 */
public interface CASL_Macro_Populate extends CASL_Macro
{
  /**
   * Returns the value of the '<em><b>Init Num</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init Num</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init Num</em>' containment reference.
   * @see #setInitNum(Expression)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getCASL_Macro_Populate_InitNum()
   * @model containment="true"
   * @generated
   */
  Expression getInitNum();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.CASL_Macro_Populate#getInitNum <em>Init Num</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init Num</em>' containment reference.
   * @see #getInitNum()
   * @generated
   */
  void setInitNum(Expression value);

  /**
   * Returns the value of the '<em><b>Ent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ent</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ent</em>' reference.
   * @see #setEnt(Entity)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getCASL_Macro_Populate_Ent()
   * @model
   * @generated
   */
  Entity getEnt();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.CASL_Macro_Populate#getEnt <em>Ent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ent</em>' reference.
   * @see #getEnt()
   * @generated
   */
  void setEnt(Entity value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getCASL_Macro_Populate_Body()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getBody();

} // CASL_Macro_Populate
