/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment_Call#getEnv <em>Env</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment_Call#getQnc <em>Qnc</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Call()
 * @model
 * @generated
 */
public interface Environment_Call extends EObject
{
  /**
   * Returns the value of the '<em><b>Env</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env</em>' reference.
   * @see #setEnv(Environment)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Call_Env()
   * @model
   * @generated
   */
  Environment getEnv();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment_Call#getEnv <em>Env</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env</em>' reference.
   * @see #getEnv()
   * @generated
   */
  void setEnv(Environment value);

  /**
   * Returns the value of the '<em><b>Qnc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Qnc</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qnc</em>' attribute.
   * @see #setQnc(String)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Call_Qnc()
   * @model
   * @generated
   */
  String getQnc();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment_Call#getQnc <em>Qnc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qnc</em>' attribute.
   * @see #getQnc()
   * @generated
   */
  void setQnc(String value);

} // Environment_Call
