/**
 * generated by Xtext 2.12.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Type Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment_Type_Name#getEnvironment_type_name <em>Environment type name</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Type_Name()
 * @model
 * @generated
 */
public interface Environment_Type_Name extends EObject
{
  /**
   * Returns the value of the '<em><b>Environment type name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Environment type name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environment type name</em>' attribute.
   * @see #setEnvironment_type_name(String)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Type_Name_Environment_type_name()
   * @model
   * @generated
   */
  String getEnvironment_type_name();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment_Type_Name#getEnvironment_type_name <em>Environment type name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Environment type name</em>' attribute.
   * @see #getEnvironment_type_name()
   * @generated
   */
  void setEnvironment_type_name(String value);

} // Environment_Type_Name
