/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_attributes <em>Env attributes</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_parameters <em>Env parameters</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_functions <em>Env functions</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_behaviors <em>Env behaviors</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_interactions <em>Env interactions</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_adaptation <em>Env adaptation</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_subSystems <em>Env sub Systems</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment#getEnv_groupinteractions <em>Env groupinteractions</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment()
 * @model
 * @generated
 */
public interface Environment extends Entity
{
  /**
   * Returns the value of the '<em><b>Env attributes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env attributes</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env attributes</em>' containment reference.
   * @see #setEnv_attributes(Environment_Rules)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_attributes()
   * @model containment="true"
   * @generated
   */
  Environment_Rules getEnv_attributes();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_attributes <em>Env attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env attributes</em>' containment reference.
   * @see #getEnv_attributes()
   * @generated
   */
  void setEnv_attributes(Environment_Rules value);

  /**
   * Returns the value of the '<em><b>Env parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env parameters</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env parameters</em>' containment reference.
   * @see #setEnv_parameters(Parameters)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_parameters()
   * @model containment="true"
   * @generated
   */
  Parameters getEnv_parameters();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_parameters <em>Env parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env parameters</em>' containment reference.
   * @see #getEnv_parameters()
   * @generated
   */
  void setEnv_parameters(Parameters value);

  /**
   * Returns the value of the '<em><b>Env functions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env functions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env functions</em>' containment reference.
   * @see #setEnv_functions(Functions)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_functions()
   * @model containment="true"
   * @generated
   */
  Functions getEnv_functions();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_functions <em>Env functions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env functions</em>' containment reference.
   * @see #getEnv_functions()
   * @generated
   */
  void setEnv_functions(Functions value);

  /**
   * Returns the value of the '<em><b>Env behaviors</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env behaviors</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env behaviors</em>' containment reference.
   * @see #setEnv_behaviors(Behaviors)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_behaviors()
   * @model containment="true"
   * @generated
   */
  Behaviors getEnv_behaviors();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_behaviors <em>Env behaviors</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env behaviors</em>' containment reference.
   * @see #getEnv_behaviors()
   * @generated
   */
  void setEnv_behaviors(Behaviors value);

  /**
   * Returns the value of the '<em><b>Env interactions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env interactions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env interactions</em>' containment reference.
   * @see #setEnv_interactions(EnvironmentInteractions)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_interactions()
   * @model containment="true"
   * @generated
   */
  EnvironmentInteractions getEnv_interactions();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_interactions <em>Env interactions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env interactions</em>' containment reference.
   * @see #getEnv_interactions()
   * @generated
   */
  void setEnv_interactions(EnvironmentInteractions value);

  /**
   * Returns the value of the '<em><b>Env adaptation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env adaptation</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env adaptation</em>' containment reference.
   * @see #setEnv_adaptation(AdaptiveProcesses)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_adaptation()
   * @model containment="true"
   * @generated
   */
  AdaptiveProcesses getEnv_adaptation();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_adaptation <em>Env adaptation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env adaptation</em>' containment reference.
   * @see #getEnv_adaptation()
   * @generated
   */
  void setEnv_adaptation(AdaptiveProcesses value);

  /**
   * Returns the value of the '<em><b>Env sub Systems</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env sub Systems</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env sub Systems</em>' containment reference.
   * @see #setEnv_subSystems(SubSystems)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_subSystems()
   * @model containment="true"
   * @generated
   */
  SubSystems getEnv_subSystems();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_subSystems <em>Env sub Systems</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env sub Systems</em>' containment reference.
   * @see #getEnv_subSystems()
   * @generated
   */
  void setEnv_subSystems(SubSystems value);

  /**
   * Returns the value of the '<em><b>Env groupinteractions</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env groupinteractions</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env groupinteractions</em>' containment reference.
   * @see #setEnv_groupinteractions(EGInteractions)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Env_groupinteractions()
   * @model containment="true"
   * @generated
   */
  EGInteractions getEnv_groupinteractions();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Environment#getEnv_groupinteractions <em>Env groupinteractions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env groupinteractions</em>' containment reference.
   * @see #getEnv_groupinteractions()
   * @generated
   */
  void setEnv_groupinteractions(EGInteractions value);

} // Environment
