/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.Environment_Types#getEnvironment_types <em>Environment types</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Types()
 * @model
 * @generated
 */
public interface Environment_Types extends EObject
{
  /**
   * Returns the value of the '<em><b>Environment types</b></em>' containment reference list.
   * The list contents are of type {@link uofa.lbirdsey.castle.casl.Environment_Type_Name}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Environment types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Environment types</em>' containment reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironment_Types_Environment_types()
   * @model containment="true"
   * @generated
   */
  EList<Environment_Type_Name> getEnvironment_types();

} // Environment_Types
