/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Environment Field Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.EnvironmentFieldReference#getEnv <em>Env</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.EnvironmentFieldReference#getAssignment <em>Assignment</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironmentFieldReference()
 * @model
 * @generated
 */
public interface EnvironmentFieldReference extends Symbol
{
  /**
   * Returns the value of the '<em><b>Env</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Env</em>' reference.
   * @see #setEnv(Environment)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironmentFieldReference_Env()
   * @model
   * @generated
   */
  Environment getEnv();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.EnvironmentFieldReference#getEnv <em>Env</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Env</em>' reference.
   * @see #getEnv()
   * @generated
   */
  void setEnv(Environment value);

  /**
   * Returns the value of the '<em><b>Assignment</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assignment</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assignment</em>' containment reference.
   * @see #setAssignment(Expression)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getEnvironmentFieldReference_Assignment()
   * @model containment="true"
   * @generated
   */
  Expression getAssignment();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.EnvironmentFieldReference#getAssignment <em>Assignment</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assignment</em>' containment reference.
   * @see #getAssignment()
   * @generated
   */
  void setAssignment(Expression value);

} // EnvironmentFieldReference
