/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Formula</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.Formula#getSym <em>Sym</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Formula#getObjField <em>Obj Field</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Formula#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getFormula()
 * @model
 * @generated
 */
public interface Formula extends EObject
{
  /**
   * Returns the value of the '<em><b>Sym</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sym</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sym</em>' reference.
   * @see #setSym(Symbol)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getFormula_Sym()
   * @model
   * @generated
   */
  Symbol getSym();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Formula#getSym <em>Sym</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sym</em>' reference.
   * @see #getSym()
   * @generated
   */
  void setSym(Symbol value);

  /**
   * Returns the value of the '<em><b>Obj Field</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Obj Field</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Obj Field</em>' reference.
   * @see #setObjField(Symbol)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getFormula_ObjField()
   * @model
   * @generated
   */
  Symbol getObjField();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Formula#getObjField <em>Obj Field</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Obj Field</em>' reference.
   * @see #getObjField()
   * @generated
   */
  void setObjField(Symbol value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getFormula_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.Formula#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

} // Formula
