/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.FunctionCallExpr#getFuncCall <em>Func Call</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getFunctionCallExpr()
 * @model
 * @generated
 */
public interface FunctionCallExpr extends Expression
{
  /**
   * Returns the value of the '<em><b>Func Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Func Call</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func Call</em>' containment reference.
   * @see #setFuncCall(FunctionCall)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getFunctionCallExpr_FuncCall()
   * @model containment="true"
   * @generated
   */
  FunctionCall getFuncCall();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.FunctionCallExpr#getFuncCall <em>Func Call</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func Call</em>' containment reference.
   * @see #getFuncCall()
   * @generated
   */
  void setFuncCall(FunctionCall value);

} // FunctionCallExpr
