/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group Internals</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.GroupInternals#getInternals <em>Internals</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getGroupInternals()
 * @model
 * @generated
 */
public interface GroupInternals extends EObject
{
  /**
   * Returns the value of the '<em><b>Internals</b></em>' containment reference list.
   * The list contents are of type {@link uofa.lbirdsey.castle.casl.GroupInternal}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Internals</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Internals</em>' containment reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getGroupInternals_Internals()
   * @model containment="true"
   * @generated
   */
  EList<GroupInternal> getInternals();

} // GroupInternals
