/**
 * generated by Xtext 2.12.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group External Interactions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.GroupExternalInteractions#getExternal_interactions <em>External interactions</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getGroupExternalInteractions()
 * @model
 * @generated
 */
public interface GroupExternalInteractions extends EObject
{
  /**
   * Returns the value of the '<em><b>External interactions</b></em>' containment reference list.
   * The list contents are of type {@link uofa.lbirdsey.castle.casl.GroupExternalInteraction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>External interactions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>External interactions</em>' containment reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getGroupExternalInteractions_External_interactions()
   * @model containment="true"
   * @generated
   */
  EList<GroupExternalInteraction> getExternal_interactions();

} // GroupExternalInteractions
