/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group Internal Interactions</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.GroupInternalInteractions#getInternal_interactions <em>Internal interactions</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getGroupInternalInteractions()
 * @model
 * @generated
 */
public interface GroupInternalInteractions extends EObject
{
  /**
   * Returns the value of the '<em><b>Internal interactions</b></em>' containment reference list.
   * The list contents are of type {@link uofa.lbirdsey.castle.casl.GroupInternalInteraction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Internal interactions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Internal interactions</em>' containment reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getGroupInternalInteractions_Internal_interactions()
   * @model containment="true"
   * @generated
   */
  EList<GroupInternalInteraction> getInternal_interactions();

} // GroupInternalInteractions
