/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Non Primitive Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.NonPrimitiveType#getCustom <em>Custom</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getNonPrimitiveType()
 * @model
 * @generated
 */
public interface NonPrimitiveType extends Type, AbstractElement
{
  /**
   * Returns the value of the '<em><b>Custom</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Custom</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Custom</em>' attribute.
   * @see #setCustom(String)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getNonPrimitiveType_Custom()
   * @model
   * @generated
   */
  String getCustom();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.NonPrimitiveType#getCustom <em>Custom</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Custom</em>' attribute.
   * @see #getCustom()
   * @generated
   */
  void setCustom(String value);

} // NonPrimitiveType
