/**
 * generated by Xtext 2.13.0
 */
package uofa.lbirdsey.castle.casl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.Object#getUseType <em>Use Type</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.Object#getFields <em>Fields</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getObject()
 * @model
 * @generated
 */
public interface Object extends NonPrimitiveType
{
  /**
   * Returns the value of the '<em><b>Use Type</b></em>' reference list.
   * The list contents are of type {@link uofa.lbirdsey.castle.casl.Object}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Use Type</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Use Type</em>' reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getObject_UseType()
   * @model
   * @generated
   */
  EList<Object> getUseType();

  /**
   * Returns the value of the '<em><b>Fields</b></em>' containment reference list.
   * The list contents are of type {@link uofa.lbirdsey.castle.casl.Entity_Feature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fields</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fields</em>' containment reference list.
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getObject_Fields()
   * @model containment="true"
   * @generated
   */
  EList<Entity_Feature> getFields();

} // Object
