/**
 * generated by Xtext 2.13.0
 */
package uofa.lbirdsey.castle.casl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Call Obj</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.SystemCallObj#getSysCall <em>Sys Call</em>}</li>
 * </ul>
 *
 * @see uofa.lbirdsey.castle.casl.CaslPackage#getSystemCallObj()
 * @model
 * @generated
 */
public interface SystemCallObj extends Expression
{
  /**
   * Returns the value of the '<em><b>Sys Call</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sys Call</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sys Call</em>' containment reference.
   * @see #setSysCall(SystemCall)
   * @see uofa.lbirdsey.castle.casl.CaslPackage#getSystemCallObj_SysCall()
   * @model containment="true"
   * @generated
   */
  SystemCall getSysCall();

  /**
   * Sets the value of the '{@link uofa.lbirdsey.castle.casl.SystemCallObj#getSysCall <em>Sys Call</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sys Call</em>' containment reference.
   * @see #getSysCall()
   * @generated
   */
  void setSysCall(SystemCall value);

} // SystemCallObj
