/**
 * generated by Xtext 2.13.0
 */
package uofa.lbirdsey.castle.casl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uofa.lbirdsey.castle.casl.AdaptiveProcesses;
import uofa.lbirdsey.castle.casl.Agent;
import uofa.lbirdsey.castle.casl.AgentInteractions;
import uofa.lbirdsey.castle.casl.Behaviors;
import uofa.lbirdsey.castle.casl.CaslPackage;
import uofa.lbirdsey.castle.casl.Functions;
import uofa.lbirdsey.castle.casl.Parameters;
import uofa.lbirdsey.castle.casl.SubSystems;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Agent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.AgentImpl#getAgent_parameters <em>Agent parameters</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.AgentImpl#getAgent_functions <em>Agent functions</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.AgentImpl#getAgent_behaviors <em>Agent behaviors</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.AgentImpl#getAgent_interactions <em>Agent interactions</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.AgentImpl#getAgent_adaptation <em>Agent adaptation</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.AgentImpl#getAgent_subSystems <em>Agent sub Systems</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AgentImpl extends EntityImpl implements Agent
{
  /**
   * The cached value of the '{@link #getAgent_parameters() <em>Agent parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent_parameters()
   * @generated
   * @ordered
   */
  protected Parameters agent_parameters;

  /**
   * The cached value of the '{@link #getAgent_functions() <em>Agent functions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent_functions()
   * @generated
   * @ordered
   */
  protected Functions agent_functions;

  /**
   * The cached value of the '{@link #getAgent_behaviors() <em>Agent behaviors</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent_behaviors()
   * @generated
   * @ordered
   */
  protected Behaviors agent_behaviors;

  /**
   * The cached value of the '{@link #getAgent_interactions() <em>Agent interactions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent_interactions()
   * @generated
   * @ordered
   */
  protected AgentInteractions agent_interactions;

  /**
   * The cached value of the '{@link #getAgent_adaptation() <em>Agent adaptation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent_adaptation()
   * @generated
   * @ordered
   */
  protected AdaptiveProcesses agent_adaptation;

  /**
   * The cached value of the '{@link #getAgent_subSystems() <em>Agent sub Systems</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent_subSystems()
   * @generated
   * @ordered
   */
  protected SubSystems agent_subSystems;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AgentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CaslPackage.eINSTANCE.getAgent();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parameters getAgent_parameters()
  {
    return agent_parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgent_parameters(Parameters newAgent_parameters, NotificationChain msgs)
  {
    Parameters oldAgent_parameters = agent_parameters;
    agent_parameters = newAgent_parameters;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_PARAMETERS, oldAgent_parameters, newAgent_parameters);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent_parameters(Parameters newAgent_parameters)
  {
    if (newAgent_parameters != agent_parameters)
    {
      NotificationChain msgs = null;
      if (agent_parameters != null)
        msgs = ((InternalEObject)agent_parameters).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_PARAMETERS, null, msgs);
      if (newAgent_parameters != null)
        msgs = ((InternalEObject)newAgent_parameters).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_PARAMETERS, null, msgs);
      msgs = basicSetAgent_parameters(newAgent_parameters, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_PARAMETERS, newAgent_parameters, newAgent_parameters));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Functions getAgent_functions()
  {
    return agent_functions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgent_functions(Functions newAgent_functions, NotificationChain msgs)
  {
    Functions oldAgent_functions = agent_functions;
    agent_functions = newAgent_functions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_FUNCTIONS, oldAgent_functions, newAgent_functions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent_functions(Functions newAgent_functions)
  {
    if (newAgent_functions != agent_functions)
    {
      NotificationChain msgs = null;
      if (agent_functions != null)
        msgs = ((InternalEObject)agent_functions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_FUNCTIONS, null, msgs);
      if (newAgent_functions != null)
        msgs = ((InternalEObject)newAgent_functions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_FUNCTIONS, null, msgs);
      msgs = basicSetAgent_functions(newAgent_functions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_FUNCTIONS, newAgent_functions, newAgent_functions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Behaviors getAgent_behaviors()
  {
    return agent_behaviors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgent_behaviors(Behaviors newAgent_behaviors, NotificationChain msgs)
  {
    Behaviors oldAgent_behaviors = agent_behaviors;
    agent_behaviors = newAgent_behaviors;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_BEHAVIORS, oldAgent_behaviors, newAgent_behaviors);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent_behaviors(Behaviors newAgent_behaviors)
  {
    if (newAgent_behaviors != agent_behaviors)
    {
      NotificationChain msgs = null;
      if (agent_behaviors != null)
        msgs = ((InternalEObject)agent_behaviors).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_BEHAVIORS, null, msgs);
      if (newAgent_behaviors != null)
        msgs = ((InternalEObject)newAgent_behaviors).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_BEHAVIORS, null, msgs);
      msgs = basicSetAgent_behaviors(newAgent_behaviors, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_BEHAVIORS, newAgent_behaviors, newAgent_behaviors));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AgentInteractions getAgent_interactions()
  {
    return agent_interactions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgent_interactions(AgentInteractions newAgent_interactions, NotificationChain msgs)
  {
    AgentInteractions oldAgent_interactions = agent_interactions;
    agent_interactions = newAgent_interactions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_INTERACTIONS, oldAgent_interactions, newAgent_interactions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent_interactions(AgentInteractions newAgent_interactions)
  {
    if (newAgent_interactions != agent_interactions)
    {
      NotificationChain msgs = null;
      if (agent_interactions != null)
        msgs = ((InternalEObject)agent_interactions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_INTERACTIONS, null, msgs);
      if (newAgent_interactions != null)
        msgs = ((InternalEObject)newAgent_interactions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_INTERACTIONS, null, msgs);
      msgs = basicSetAgent_interactions(newAgent_interactions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_INTERACTIONS, newAgent_interactions, newAgent_interactions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public AdaptiveProcesses getAgent_adaptation()
  {
    return agent_adaptation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgent_adaptation(AdaptiveProcesses newAgent_adaptation, NotificationChain msgs)
  {
    AdaptiveProcesses oldAgent_adaptation = agent_adaptation;
    agent_adaptation = newAgent_adaptation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_ADAPTATION, oldAgent_adaptation, newAgent_adaptation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent_adaptation(AdaptiveProcesses newAgent_adaptation)
  {
    if (newAgent_adaptation != agent_adaptation)
    {
      NotificationChain msgs = null;
      if (agent_adaptation != null)
        msgs = ((InternalEObject)agent_adaptation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_ADAPTATION, null, msgs);
      if (newAgent_adaptation != null)
        msgs = ((InternalEObject)newAgent_adaptation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_ADAPTATION, null, msgs);
      msgs = basicSetAgent_adaptation(newAgent_adaptation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_ADAPTATION, newAgent_adaptation, newAgent_adaptation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SubSystems getAgent_subSystems()
  {
    return agent_subSystems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgent_subSystems(SubSystems newAgent_subSystems, NotificationChain msgs)
  {
    SubSystems oldAgent_subSystems = agent_subSystems;
    agent_subSystems = newAgent_subSystems;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_SUB_SYSTEMS, oldAgent_subSystems, newAgent_subSystems);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent_subSystems(SubSystems newAgent_subSystems)
  {
    if (newAgent_subSystems != agent_subSystems)
    {
      NotificationChain msgs = null;
      if (agent_subSystems != null)
        msgs = ((InternalEObject)agent_subSystems).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_SUB_SYSTEMS, null, msgs);
      if (newAgent_subSystems != null)
        msgs = ((InternalEObject)newAgent_subSystems).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.AGENT__AGENT_SUB_SYSTEMS, null, msgs);
      msgs = basicSetAgent_subSystems(newAgent_subSystems, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.AGENT__AGENT_SUB_SYSTEMS, newAgent_subSystems, newAgent_subSystems));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CaslPackage.AGENT__AGENT_PARAMETERS:
        return basicSetAgent_parameters(null, msgs);
      case CaslPackage.AGENT__AGENT_FUNCTIONS:
        return basicSetAgent_functions(null, msgs);
      case CaslPackage.AGENT__AGENT_BEHAVIORS:
        return basicSetAgent_behaviors(null, msgs);
      case CaslPackage.AGENT__AGENT_INTERACTIONS:
        return basicSetAgent_interactions(null, msgs);
      case CaslPackage.AGENT__AGENT_ADAPTATION:
        return basicSetAgent_adaptation(null, msgs);
      case CaslPackage.AGENT__AGENT_SUB_SYSTEMS:
        return basicSetAgent_subSystems(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CaslPackage.AGENT__AGENT_PARAMETERS:
        return getAgent_parameters();
      case CaslPackage.AGENT__AGENT_FUNCTIONS:
        return getAgent_functions();
      case CaslPackage.AGENT__AGENT_BEHAVIORS:
        return getAgent_behaviors();
      case CaslPackage.AGENT__AGENT_INTERACTIONS:
        return getAgent_interactions();
      case CaslPackage.AGENT__AGENT_ADAPTATION:
        return getAgent_adaptation();
      case CaslPackage.AGENT__AGENT_SUB_SYSTEMS:
        return getAgent_subSystems();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CaslPackage.AGENT__AGENT_PARAMETERS:
        setAgent_parameters((Parameters)newValue);
        return;
      case CaslPackage.AGENT__AGENT_FUNCTIONS:
        setAgent_functions((Functions)newValue);
        return;
      case CaslPackage.AGENT__AGENT_BEHAVIORS:
        setAgent_behaviors((Behaviors)newValue);
        return;
      case CaslPackage.AGENT__AGENT_INTERACTIONS:
        setAgent_interactions((AgentInteractions)newValue);
        return;
      case CaslPackage.AGENT__AGENT_ADAPTATION:
        setAgent_adaptation((AdaptiveProcesses)newValue);
        return;
      case CaslPackage.AGENT__AGENT_SUB_SYSTEMS:
        setAgent_subSystems((SubSystems)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.AGENT__AGENT_PARAMETERS:
        setAgent_parameters((Parameters)null);
        return;
      case CaslPackage.AGENT__AGENT_FUNCTIONS:
        setAgent_functions((Functions)null);
        return;
      case CaslPackage.AGENT__AGENT_BEHAVIORS:
        setAgent_behaviors((Behaviors)null);
        return;
      case CaslPackage.AGENT__AGENT_INTERACTIONS:
        setAgent_interactions((AgentInteractions)null);
        return;
      case CaslPackage.AGENT__AGENT_ADAPTATION:
        setAgent_adaptation((AdaptiveProcesses)null);
        return;
      case CaslPackage.AGENT__AGENT_SUB_SYSTEMS:
        setAgent_subSystems((SubSystems)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.AGENT__AGENT_PARAMETERS:
        return agent_parameters != null;
      case CaslPackage.AGENT__AGENT_FUNCTIONS:
        return agent_functions != null;
      case CaslPackage.AGENT__AGENT_BEHAVIORS:
        return agent_behaviors != null;
      case CaslPackage.AGENT__AGENT_INTERACTIONS:
        return agent_interactions != null;
      case CaslPackage.AGENT__AGENT_ADAPTATION:
        return agent_adaptation != null;
      case CaslPackage.AGENT__AGENT_SUB_SYSTEMS:
        return agent_subSystems != null;
    }
    return super.eIsSet(featureID);
  }

} //AgentImpl
