/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uofa.lbirdsey.castle.casl.CaslPackage;
import uofa.lbirdsey.castle.casl.Environment;
import uofa.lbirdsey.castle.casl.Environment_Call;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Environment Call</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.Environment_CallImpl#getEnv <em>Env</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.Environment_CallImpl#getQnc <em>Qnc</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Environment_CallImpl extends MinimalEObjectImpl.Container implements Environment_Call
{
  /**
   * The cached value of the '{@link #getEnv() <em>Env</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnv()
   * @generated
   * @ordered
   */
  protected Environment env;

  /**
   * The default value of the '{@link #getQnc() <em>Qnc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQnc()
   * @generated
   * @ordered
   */
  protected static final String QNC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getQnc() <em>Qnc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQnc()
   * @generated
   * @ordered
   */
  protected String qnc = QNC_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Environment_CallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CaslPackage.eINSTANCE.getEnvironment_Call();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Environment getEnv()
  {
    if (env != null && env.eIsProxy())
    {
      InternalEObject oldEnv = (InternalEObject)env;
      env = (Environment)eResolveProxy(oldEnv);
      if (env != oldEnv)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, CaslPackage.ENVIRONMENT_CALL__ENV, oldEnv, env));
      }
    }
    return env;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Environment basicGetEnv()
  {
    return env;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnv(Environment newEnv)
  {
    Environment oldEnv = env;
    env = newEnv;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.ENVIRONMENT_CALL__ENV, oldEnv, env));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getQnc()
  {
    return qnc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setQnc(String newQnc)
  {
    String oldQnc = qnc;
    qnc = newQnc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.ENVIRONMENT_CALL__QNC, oldQnc, qnc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CaslPackage.ENVIRONMENT_CALL__ENV:
        if (resolve) return getEnv();
        return basicGetEnv();
      case CaslPackage.ENVIRONMENT_CALL__QNC:
        return getQnc();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CaslPackage.ENVIRONMENT_CALL__ENV:
        setEnv((Environment)newValue);
        return;
      case CaslPackage.ENVIRONMENT_CALL__QNC:
        setQnc((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.ENVIRONMENT_CALL__ENV:
        setEnv((Environment)null);
        return;
      case CaslPackage.ENVIRONMENT_CALL__QNC:
        setQnc(QNC_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.ENVIRONMENT_CALL__ENV:
        return env != null;
      case CaslPackage.ENVIRONMENT_CALL__QNC:
        return QNC_EDEFAULT == null ? qnc != null : !QNC_EDEFAULT.equals(qnc);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (qnc: ");
    result.append(qnc);
    result.append(')');
    return result.toString();
  }

} //Environment_CallImpl
