/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl.impl;

import org.eclipse.emf.ecore.EClass;

import uofa.lbirdsey.castle.casl.CaslPackage;
import uofa.lbirdsey.castle.casl.EnvironmentInteraction;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Environment Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class EnvironmentInteractionImpl extends InteractionImpl implements EnvironmentInteraction
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnvironmentInteractionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CaslPackage.eINSTANCE.getEnvironmentInteraction();
  }

} //EnvironmentInteractionImpl
