/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uofa.lbirdsey.castle.casl.CaslPackage;
import uofa.lbirdsey.castle.casl.SystemCall;
import uofa.lbirdsey.castle.casl.SystemCallObj;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System Call Obj</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemCallObjImpl#getSysCall <em>Sys Call</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SystemCallObjImpl extends ExpressionImpl implements SystemCallObj
{
  /**
   * The cached value of the '{@link #getSysCall() <em>Sys Call</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSysCall()
   * @generated
   * @ordered
   */
  protected SystemCall sysCall;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SystemCallObjImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CaslPackage.eINSTANCE.getSystemCallObj();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SystemCall getSysCall()
  {
    return sysCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSysCall(SystemCall newSysCall, NotificationChain msgs)
  {
    SystemCall oldSysCall = sysCall;
    sysCall = newSysCall;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL, oldSysCall, newSysCall);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSysCall(SystemCall newSysCall)
  {
    if (newSysCall != sysCall)
    {
      NotificationChain msgs = null;
      if (sysCall != null)
        msgs = ((InternalEObject)sysCall).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL, null, msgs);
      if (newSysCall != null)
        msgs = ((InternalEObject)newSysCall).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL, null, msgs);
      msgs = basicSetSysCall(newSysCall, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL, newSysCall, newSysCall));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL:
        return basicSetSysCall(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL:
        return getSysCall();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL:
        setSysCall((SystemCall)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL:
        setSysCall((SystemCall)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM_CALL_OBJ__SYS_CALL:
        return sysCall != null;
    }
    return super.eIsSet(featureID);
  }

} //SystemCallObjImpl
