/**
 * generated by Xtext 2.11.0
 */
package uofa.lbirdsey.castle.casl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uofa.lbirdsey.castle.casl.Agent_Types;
import uofa.lbirdsey.castle.casl.CAS_Rules;
import uofa.lbirdsey.castle.casl.CaslPackage;
import uofa.lbirdsey.castle.casl.End_Conditions;
import uofa.lbirdsey.castle.casl.Environment_Types;
import uofa.lbirdsey.castle.casl.Functions;
import uofa.lbirdsey.castle.casl.Group_Types;
import uofa.lbirdsey.castle.casl.Parameters;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>System</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getName <em>Name</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getDesc <em>Desc</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getCas_rules <em>Cas rules</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getSystem_parameters <em>System parameters</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getSystem_functions <em>System functions</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getAgent_types <em>Agent types</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getGroup_types <em>Group types</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getEnvironment_types <em>Environment types</em>}</li>
 *   <li>{@link uofa.lbirdsey.castle.casl.impl.SystemImpl#getEnd_conditions <em>End conditions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SystemImpl extends MinimalEObjectImpl.Container implements uofa.lbirdsey.castle.casl.System
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getDesc() <em>Desc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDesc()
   * @generated
   * @ordered
   */
  protected static final String DESC_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDesc() <em>Desc</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDesc()
   * @generated
   * @ordered
   */
  protected String desc = DESC_EDEFAULT;

  /**
   * The cached value of the '{@link #getCas_rules() <em>Cas rules</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCas_rules()
   * @generated
   * @ordered
   */
  protected CAS_Rules cas_rules;

  /**
   * The cached value of the '{@link #getSystem_parameters() <em>System parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSystem_parameters()
   * @generated
   * @ordered
   */
  protected Parameters system_parameters;

  /**
   * The cached value of the '{@link #getSystem_functions() <em>System functions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSystem_functions()
   * @generated
   * @ordered
   */
  protected Functions system_functions;

  /**
   * The cached value of the '{@link #getAgent_types() <em>Agent types</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAgent_types()
   * @generated
   * @ordered
   */
  protected Agent_Types agent_types;

  /**
   * The cached value of the '{@link #getGroup_types() <em>Group types</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGroup_types()
   * @generated
   * @ordered
   */
  protected Group_Types group_types;

  /**
   * The cached value of the '{@link #getEnvironment_types() <em>Environment types</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnvironment_types()
   * @generated
   * @ordered
   */
  protected Environment_Types environment_types;

  /**
   * The cached value of the '{@link #getEnd_conditions() <em>End conditions</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnd_conditions()
   * @generated
   * @ordered
   */
  protected End_Conditions end_conditions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SystemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CaslPackage.eINSTANCE.getSystem();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDesc()
  {
    return desc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDesc(String newDesc)
  {
    String oldDesc = desc;
    desc = newDesc;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__DESC, oldDesc, desc));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CAS_Rules getCas_rules()
  {
    return cas_rules;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCas_rules(CAS_Rules newCas_rules, NotificationChain msgs)
  {
    CAS_Rules oldCas_rules = cas_rules;
    cas_rules = newCas_rules;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__CAS_RULES, oldCas_rules, newCas_rules);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setCas_rules(CAS_Rules newCas_rules)
  {
    if (newCas_rules != cas_rules)
    {
      NotificationChain msgs = null;
      if (cas_rules != null)
        msgs = ((InternalEObject)cas_rules).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__CAS_RULES, null, msgs);
      if (newCas_rules != null)
        msgs = ((InternalEObject)newCas_rules).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__CAS_RULES, null, msgs);
      msgs = basicSetCas_rules(newCas_rules, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__CAS_RULES, newCas_rules, newCas_rules));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parameters getSystem_parameters()
  {
    return system_parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSystem_parameters(Parameters newSystem_parameters, NotificationChain msgs)
  {
    Parameters oldSystem_parameters = system_parameters;
    system_parameters = newSystem_parameters;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__SYSTEM_PARAMETERS, oldSystem_parameters, newSystem_parameters);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSystem_parameters(Parameters newSystem_parameters)
  {
    if (newSystem_parameters != system_parameters)
    {
      NotificationChain msgs = null;
      if (system_parameters != null)
        msgs = ((InternalEObject)system_parameters).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__SYSTEM_PARAMETERS, null, msgs);
      if (newSystem_parameters != null)
        msgs = ((InternalEObject)newSystem_parameters).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__SYSTEM_PARAMETERS, null, msgs);
      msgs = basicSetSystem_parameters(newSystem_parameters, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__SYSTEM_PARAMETERS, newSystem_parameters, newSystem_parameters));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Functions getSystem_functions()
  {
    return system_functions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSystem_functions(Functions newSystem_functions, NotificationChain msgs)
  {
    Functions oldSystem_functions = system_functions;
    system_functions = newSystem_functions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__SYSTEM_FUNCTIONS, oldSystem_functions, newSystem_functions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSystem_functions(Functions newSystem_functions)
  {
    if (newSystem_functions != system_functions)
    {
      NotificationChain msgs = null;
      if (system_functions != null)
        msgs = ((InternalEObject)system_functions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__SYSTEM_FUNCTIONS, null, msgs);
      if (newSystem_functions != null)
        msgs = ((InternalEObject)newSystem_functions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__SYSTEM_FUNCTIONS, null, msgs);
      msgs = basicSetSystem_functions(newSystem_functions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__SYSTEM_FUNCTIONS, newSystem_functions, newSystem_functions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Agent_Types getAgent_types()
  {
    return agent_types;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAgent_types(Agent_Types newAgent_types, NotificationChain msgs)
  {
    Agent_Types oldAgent_types = agent_types;
    agent_types = newAgent_types;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__AGENT_TYPES, oldAgent_types, newAgent_types);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAgent_types(Agent_Types newAgent_types)
  {
    if (newAgent_types != agent_types)
    {
      NotificationChain msgs = null;
      if (agent_types != null)
        msgs = ((InternalEObject)agent_types).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__AGENT_TYPES, null, msgs);
      if (newAgent_types != null)
        msgs = ((InternalEObject)newAgent_types).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__AGENT_TYPES, null, msgs);
      msgs = basicSetAgent_types(newAgent_types, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__AGENT_TYPES, newAgent_types, newAgent_types));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Group_Types getGroup_types()
  {
    return group_types;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetGroup_types(Group_Types newGroup_types, NotificationChain msgs)
  {
    Group_Types oldGroup_types = group_types;
    group_types = newGroup_types;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__GROUP_TYPES, oldGroup_types, newGroup_types);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGroup_types(Group_Types newGroup_types)
  {
    if (newGroup_types != group_types)
    {
      NotificationChain msgs = null;
      if (group_types != null)
        msgs = ((InternalEObject)group_types).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__GROUP_TYPES, null, msgs);
      if (newGroup_types != null)
        msgs = ((InternalEObject)newGroup_types).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__GROUP_TYPES, null, msgs);
      msgs = basicSetGroup_types(newGroup_types, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__GROUP_TYPES, newGroup_types, newGroup_types));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Environment_Types getEnvironment_types()
  {
    return environment_types;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnvironment_types(Environment_Types newEnvironment_types, NotificationChain msgs)
  {
    Environment_Types oldEnvironment_types = environment_types;
    environment_types = newEnvironment_types;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__ENVIRONMENT_TYPES, oldEnvironment_types, newEnvironment_types);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnvironment_types(Environment_Types newEnvironment_types)
  {
    if (newEnvironment_types != environment_types)
    {
      NotificationChain msgs = null;
      if (environment_types != null)
        msgs = ((InternalEObject)environment_types).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__ENVIRONMENT_TYPES, null, msgs);
      if (newEnvironment_types != null)
        msgs = ((InternalEObject)newEnvironment_types).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__ENVIRONMENT_TYPES, null, msgs);
      msgs = basicSetEnvironment_types(newEnvironment_types, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__ENVIRONMENT_TYPES, newEnvironment_types, newEnvironment_types));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public End_Conditions getEnd_conditions()
  {
    return end_conditions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEnd_conditions(End_Conditions newEnd_conditions, NotificationChain msgs)
  {
    End_Conditions oldEnd_conditions = end_conditions;
    end_conditions = newEnd_conditions;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__END_CONDITIONS, oldEnd_conditions, newEnd_conditions);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnd_conditions(End_Conditions newEnd_conditions)
  {
    if (newEnd_conditions != end_conditions)
    {
      NotificationChain msgs = null;
      if (end_conditions != null)
        msgs = ((InternalEObject)end_conditions).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__END_CONDITIONS, null, msgs);
      if (newEnd_conditions != null)
        msgs = ((InternalEObject)newEnd_conditions).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CaslPackage.SYSTEM__END_CONDITIONS, null, msgs);
      msgs = basicSetEnd_conditions(newEnd_conditions, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CaslPackage.SYSTEM__END_CONDITIONS, newEnd_conditions, newEnd_conditions));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM__CAS_RULES:
        return basicSetCas_rules(null, msgs);
      case CaslPackage.SYSTEM__SYSTEM_PARAMETERS:
        return basicSetSystem_parameters(null, msgs);
      case CaslPackage.SYSTEM__SYSTEM_FUNCTIONS:
        return basicSetSystem_functions(null, msgs);
      case CaslPackage.SYSTEM__AGENT_TYPES:
        return basicSetAgent_types(null, msgs);
      case CaslPackage.SYSTEM__GROUP_TYPES:
        return basicSetGroup_types(null, msgs);
      case CaslPackage.SYSTEM__ENVIRONMENT_TYPES:
        return basicSetEnvironment_types(null, msgs);
      case CaslPackage.SYSTEM__END_CONDITIONS:
        return basicSetEnd_conditions(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM__NAME:
        return getName();
      case CaslPackage.SYSTEM__DESC:
        return getDesc();
      case CaslPackage.SYSTEM__CAS_RULES:
        return getCas_rules();
      case CaslPackage.SYSTEM__SYSTEM_PARAMETERS:
        return getSystem_parameters();
      case CaslPackage.SYSTEM__SYSTEM_FUNCTIONS:
        return getSystem_functions();
      case CaslPackage.SYSTEM__AGENT_TYPES:
        return getAgent_types();
      case CaslPackage.SYSTEM__GROUP_TYPES:
        return getGroup_types();
      case CaslPackage.SYSTEM__ENVIRONMENT_TYPES:
        return getEnvironment_types();
      case CaslPackage.SYSTEM__END_CONDITIONS:
        return getEnd_conditions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM__NAME:
        setName((String)newValue);
        return;
      case CaslPackage.SYSTEM__DESC:
        setDesc((String)newValue);
        return;
      case CaslPackage.SYSTEM__CAS_RULES:
        setCas_rules((CAS_Rules)newValue);
        return;
      case CaslPackage.SYSTEM__SYSTEM_PARAMETERS:
        setSystem_parameters((Parameters)newValue);
        return;
      case CaslPackage.SYSTEM__SYSTEM_FUNCTIONS:
        setSystem_functions((Functions)newValue);
        return;
      case CaslPackage.SYSTEM__AGENT_TYPES:
        setAgent_types((Agent_Types)newValue);
        return;
      case CaslPackage.SYSTEM__GROUP_TYPES:
        setGroup_types((Group_Types)newValue);
        return;
      case CaslPackage.SYSTEM__ENVIRONMENT_TYPES:
        setEnvironment_types((Environment_Types)newValue);
        return;
      case CaslPackage.SYSTEM__END_CONDITIONS:
        setEnd_conditions((End_Conditions)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM__NAME:
        setName(NAME_EDEFAULT);
        return;
      case CaslPackage.SYSTEM__DESC:
        setDesc(DESC_EDEFAULT);
        return;
      case CaslPackage.SYSTEM__CAS_RULES:
        setCas_rules((CAS_Rules)null);
        return;
      case CaslPackage.SYSTEM__SYSTEM_PARAMETERS:
        setSystem_parameters((Parameters)null);
        return;
      case CaslPackage.SYSTEM__SYSTEM_FUNCTIONS:
        setSystem_functions((Functions)null);
        return;
      case CaslPackage.SYSTEM__AGENT_TYPES:
        setAgent_types((Agent_Types)null);
        return;
      case CaslPackage.SYSTEM__GROUP_TYPES:
        setGroup_types((Group_Types)null);
        return;
      case CaslPackage.SYSTEM__ENVIRONMENT_TYPES:
        setEnvironment_types((Environment_Types)null);
        return;
      case CaslPackage.SYSTEM__END_CONDITIONS:
        setEnd_conditions((End_Conditions)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CaslPackage.SYSTEM__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case CaslPackage.SYSTEM__DESC:
        return DESC_EDEFAULT == null ? desc != null : !DESC_EDEFAULT.equals(desc);
      case CaslPackage.SYSTEM__CAS_RULES:
        return cas_rules != null;
      case CaslPackage.SYSTEM__SYSTEM_PARAMETERS:
        return system_parameters != null;
      case CaslPackage.SYSTEM__SYSTEM_FUNCTIONS:
        return system_functions != null;
      case CaslPackage.SYSTEM__AGENT_TYPES:
        return agent_types != null;
      case CaslPackage.SYSTEM__GROUP_TYPES:
        return group_types != null;
      case CaslPackage.SYSTEM__ENVIRONMENT_TYPES:
        return environment_types != null;
      case CaslPackage.SYSTEM__END_CONDITIONS:
        return end_conditions != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", desc: ");
    result.append(desc);
    result.append(')');
    return result.toString();
  }

} //SystemImpl
